name: Semantic-Release

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  #build_test:
  #  if: github.event_name == 'push' && github.ref != 'refs/heads/master'
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #      
  #    - name: Build
  #      run: dotnet build -c RELEASE
  
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Release
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
